<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UMRR3LS" name="NUGUAPP_001_실행.앱시작_01" tests="12" failures="0" timestamp="19 Aug 2020 14:44:08 GMT" time="362.256" errors="1">
  <testcase name="TC_앱실행_012_from_013" time="57.175" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_014_from_015" time="49.992" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_021" time="11.670" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_007" time="27.941" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_010" time="26.777" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_008" time="2.473" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_016" time="19.130" classname="NUGUAPP_001_실행.앱시작_01">
    <error type="org.testng.SkipException" message="자동로그인 체크 여부가 사라짐">
      <![CDATA[org.testng.SkipException: 자동로그인 체크 여부가 사라짐
	at NUGUAPP_001_실행.앱시작_01.TC_앱실행_016(앱시작_01.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC_앱실행_016 -->
  <testcase name="TC_앱실행_005" time="1.460" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_004" time="16.451" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_011" time="28.928" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_017_from_018" time="70.966" classname="NUGUAPP_001_실행.앱시작_01"/>
  <testcase name="TC_앱실행_020" time="49.293" classname="NUGUAPP_001_실행.앱시작_01"/>
</testsuite> <!-- NUGUAPP_001_실행.앱시작_01 -->
